/**
 * Kapture Forms · the 40 primitive atoms.
 *
 * Every form in the catalogue — and every form an AI generator produces —
 * resolves down to a sequence of these. Adding a new atom here lights it up
 * in the builder UI, the runner, the CSV exporter, and the API automatically.
 *
 * Edit rules:
 *   - Don't change an existing id once shipped. Customer forms reference it.
 *   - Default validation should be the MINIMUM sensible bar — authors can
 *     tighten in FieldInstance.validation.
 *   - Keep the summary under 70 chars. It shows in the field picker.
 */

import type { PrimitiveSpec } from "./types";

export const PRIMITIVES: PrimitiveSpec[] = [
  // ───────── identity ─────────
  {
    id: "name-full",
    label: "Full name",
    category: "identity",
    summary: "Single-field full legal name.",
    runner: "input.text",
    csv: { columns: 1 },
    defaultValidation: { required: true, minLength: 2, maxLength: 80 },
    a11y: { autocomplete: "name", inputMode: "text" },
    legacyType: "text",
    tags: ["name", "person", "identity"],
  },
  {
    id: "name-parts",
    label: "First & last name",
    category: "identity",
    summary: "Split first / middle / last name fields.",
    runner: "compound.name-parts",
    csv: { columns: 3, columnSuffixes: ["first", "middle", "last"] },
    defaultValidation: { required: true },
    a11y: { autocomplete: "name" },
    legacyType: "compound",
    tags: ["name", "person", "kyc"],
  },
  {
    id: "email",
    label: "Email address",
    category: "identity",
    summary: "Validated email with mailto-style format check.",
    runner: "input.email",
    csv: { columns: 1, transform: "trim" },
    defaultValidation: { required: true, named: ["email"], maxLength: 254 },
    a11y: { autocomplete: "email", inputMode: "email" },
    legacyType: "email",
    tags: ["email", "contact", "identity"],
  },
  {
    id: "phone-uk",
    label: "UK phone number",
    category: "identity",
    summary: "UK mobile / landline with format validation.",
    runner: "input.tel",
    csv: { columns: 1, transform: "phone-e164" },
    defaultValidation: { required: true, pattern: "^(\\+44|0)\\s?\\d{2,4}\\s?\\d{3,4}\\s?\\d{3,4}$" },
    a11y: { autocomplete: "tel", inputMode: "tel" },
    legacyType: "tel",
    tags: ["phone", "contact", "uk"],
  },
  {
    id: "phone-intl",
    label: "International phone",
    category: "identity",
    summary: "Country dial-code prefix + national number.",
    runner: "input.tel",
    csv: { columns: 1, transform: "phone-e164" },
    defaultValidation: { required: true, named: ["intl-phone"] },
    a11y: { autocomplete: "tel", inputMode: "tel" },
    legacyType: "tel",
    tags: ["phone", "contact", "international"],
  },
  {
    id: "address-uk",
    label: "UK address",
    category: "identity",
    summary: "Line 1, line 2, town, county, postcode.",
    runner: "compound.address-uk",
    csv: {
      columns: 5,
      columnSuffixes: ["line1", "line2", "town", "county", "postcode"],
    },
    defaultValidation: { required: true },
    a11y: { autocomplete: "street-address" },
    legacyType: "compound",
    tags: ["address", "uk", "kyc"],
  },
  {
    id: "address-intl",
    label: "International address",
    category: "identity",
    summary: "Country-aware address with state / region.",
    runner: "compound.address-intl",
    csv: {
      columns: 6,
      columnSuffixes: ["line1", "line2", "city", "region", "postcode", "country"],
    },
    defaultValidation: { required: true },
    a11y: { autocomplete: "street-address" },
    legacyType: "compound",
    tags: ["address", "international"],
  },
  {
    id: "postcode-lookup",
    label: "UK postcode lookup",
    category: "advanced",
    summary: "Type postcode, pick from address suggestions.",
    runner: "compound.postcode-lookup",
    csv: {
      columns: 5,
      columnSuffixes: ["line1", "line2", "town", "county", "postcode"],
    },
    defaultValidation: { required: true, named: ["uk-postcode"] },
    a11y: { autocomplete: "postal-code" },
    legacyType: "compound",
    tags: ["address", "postcode", "uk", "lookup"],
  },

  // ───────── datetime ─────────
  {
    id: "date",
    label: "Date",
    category: "datetime",
    summary: "Date picker with ISO-8601 storage.",
    runner: "input.date",
    csv: { columns: 1, transform: "iso-date" },
    defaultValidation: { required: true },
    a11y: { inputMode: "numeric" },
    legacyType: "date",
    tags: ["date", "calendar"],
  },
  {
    id: "time",
    label: "Time",
    category: "datetime",
    summary: "24-hour time picker.",
    runner: "input.time",
    csv: { columns: 1 },
    defaultValidation: { required: true },
    a11y: { inputMode: "numeric" },
    legacyType: "text",
    tags: ["time"],
  },
  {
    id: "datetime",
    label: "Date & time",
    category: "datetime",
    summary: "Combined date + time picker.",
    runner: "input.datetime",
    csv: { columns: 1 },
    defaultValidation: { required: true },
    a11y: { inputMode: "numeric" },
    legacyType: "text",
    tags: ["datetime", "appointment"],
  },
  {
    id: "dob",
    label: "Date of birth",
    category: "datetime",
    summary: "DOB with past-date + age validation hooks.",
    runner: "input.date",
    csv: { columns: 1, transform: "iso-date" },
    defaultValidation: { required: true, named: ["past-date"] },
    a11y: { autocomplete: "bday", inputMode: "numeric" },
    legacyType: "date",
    tags: ["dob", "age", "identity"],
  },

  // ───────── choice ─────────
  {
    id: "select-single",
    label: "Dropdown — single",
    category: "choice",
    summary: "Pick one from a list of options.",
    runner: "select.single",
    csv: { columns: 1 },
    defaultValidation: { required: true },
    a11y: {},
    legacyType: "select",
    tags: ["select", "dropdown", "choice"],
  },
  {
    id: "select-multi",
    label: "Dropdown — multi",
    category: "choice",
    summary: "Pick multiple options. Stored as comma-separated.",
    runner: "select.multi",
    csv: { columns: 1 },
    defaultValidation: { required: true },
    a11y: {},
    legacyType: "multi-select",
    tags: ["select", "multi", "choice"],
  },
  {
    id: "radio",
    label: "Radio buttons",
    category: "choice",
    summary: "Inline radio group for short option lists.",
    runner: "select.radio",
    csv: { columns: 1 },
    defaultValidation: { required: true },
    a11y: {},
    legacyType: "select",
    tags: ["radio", "choice"],
  },
  {
    id: "checkbox-group",
    label: "Checkbox group",
    category: "choice",
    summary: "Multi-select rendered as checkboxes.",
    runner: "select.checkbox",
    csv: { columns: 1 },
    defaultValidation: {},
    a11y: {},
    legacyType: "multi-select",
    tags: ["checkbox", "multi", "choice"],
  },
  {
    id: "rating-stars",
    label: "Star rating",
    category: "choice",
    summary: "1–5 star rating with hover preview.",
    runner: "select.stars",
    csv: { columns: 1 },
    defaultValidation: { required: true, min: 1, max: 5 },
    a11y: {},
    legacyType: "number",
    tags: ["rating", "stars", "review"],
  },
  {
    id: "rating-numeric",
    label: "Numeric rating",
    category: "choice",
    summary: "0–10 numeric scale (NPS-style).",
    runner: "select.numeric-rating",
    csv: { columns: 1 },
    defaultValidation: { required: true, min: 0, max: 10 },
    a11y: { inputMode: "numeric" },
    legacyType: "number",
    tags: ["rating", "nps", "score"],
  },

  // ───────── text ─────────
  {
    id: "text-short",
    label: "Short text",
    category: "text",
    summary: "Single-line free text.",
    runner: "input.text",
    csv: { columns: 1, transform: "trim" },
    defaultValidation: { maxLength: 200 },
    a11y: { inputMode: "text" },
    legacyType: "text",
    tags: ["text", "input"],
  },
  {
    id: "text-long",
    label: "Long text",
    category: "text",
    summary: "Multi-line free text. Counts characters.",
    runner: "textarea",
    csv: { columns: 1, transform: "trim" },
    defaultValidation: { maxLength: 2000 },
    a11y: { inputMode: "text" },
    legacyType: "textarea",
    tags: ["textarea", "notes", "longform"],
  },
  {
    id: "password-confirm",
    label: "Password (with confirm)",
    category: "text",
    summary: "Password + repeat-password with match check.",
    runner: "compound.password-confirm",
    csv: { columns: 0 }, // never written to CSV
    defaultValidation: { required: true, minLength: 10 },
    a11y: { autocomplete: "new-password" },
    legacyType: "compound",
    tags: ["password", "auth", "security"],
  },
  {
    id: "url",
    label: "URL",
    category: "text",
    summary: "Single URL with format check.",
    runner: "input.url",
    csv: { columns: 1, transform: "trim" },
    defaultValidation: { named: ["url"], maxLength: 2048 },
    a11y: { autocomplete: "url", inputMode: "url" },
    legacyType: "text",
    tags: ["url", "link", "website"],
  },

  // ───────── numeric ─────────
  {
    id: "number",
    label: "Number",
    category: "numeric",
    summary: "Plain numeric input with min / max bounds.",
    runner: "input.number",
    csv: { columns: 1 },
    defaultValidation: {},
    a11y: { inputMode: "decimal" },
    legacyType: "number",
    tags: ["number", "numeric"],
  },
  {
    id: "currency",
    label: "Currency amount",
    category: "numeric",
    summary: "Money input with currency symbol prefix.",
    runner: "input.currency",
    csv: { columns: 1, transform: "money-pence" },
    defaultValidation: { min: 0 },
    a11y: { inputMode: "decimal" },
    legacyType: "number",
    tags: ["currency", "money", "price"],
  },
  {
    id: "percent",
    label: "Percentage",
    category: "numeric",
    summary: "0–100 percent input.",
    runner: "input.percent",
    csv: { columns: 1 },
    defaultValidation: { min: 0, max: 100 },
    a11y: { inputMode: "decimal" },
    legacyType: "number",
    tags: ["percent", "percentage"],
  },
  {
    id: "slider",
    label: "Slider",
    category: "numeric",
    summary: "Range slider for bounded numeric input.",
    runner: "input.slider",
    csv: { columns: 1 },
    defaultValidation: { min: 0, max: 100 },
    a11y: {},
    legacyType: "number",
    tags: ["slider", "range"],
  },

  // ───────── media ─────────
  {
    id: "file-upload",
    label: "File upload",
    category: "media",
    summary: "Single file — PDF, doc, image up to 25 MB.",
    runner: "upload.file",
    csv: { columns: 1 }, // stored as object-storage URL
    defaultValidation: {},
    a11y: {},
    legacyType: "text",
    tags: ["upload", "file", "attachment"],
  },
  {
    id: "file-multi",
    label: "Multiple files",
    category: "media",
    summary: "Up to 10 files, 25 MB each.",
    runner: "upload.file-multi",
    csv: { columns: 1 },
    defaultValidation: {},
    a11y: {},
    legacyType: "text",
    tags: ["upload", "files", "multi"],
  },
  {
    id: "image-upload",
    label: "Image upload",
    category: "media",
    summary: "Image-only upload with thumbnail preview.",
    runner: "upload.image",
    csv: { columns: 1 },
    defaultValidation: {},
    a11y: {},
    legacyType: "text",
    tags: ["upload", "image", "photo"],
  },
  {
    id: "signature",
    label: "Signature",
    category: "media",
    summary: "Drawn signature — saved as PNG + audit hash.",
    runner: "draw.signature",
    csv: { columns: 1 },
    defaultValidation: { required: true },
    a11y: {},
    legacyType: "signature",
    tags: ["signature", "legal", "sign"],
  },

  // ───────── payment ─────────
  {
    id: "payment-card",
    label: "Payment card",
    category: "payment",
    summary: "Card via Stripe Elements — never stored locally.",
    runner: "compound.payment-card",
    csv: { columns: 1 }, // payment intent id only
    defaultValidation: { required: true },
    a11y: { autocomplete: "cc-number" },
    legacyType: "compound",
    tags: ["payment", "card", "stripe"],
  },
  {
    id: "payment-iban",
    label: "Bank account (IBAN)",
    category: "payment",
    summary: "European bank account number with checksum validation.",
    runner: "compound.payment-iban",
    csv: { columns: 1 },
    defaultValidation: { required: true, named: ["iban"] },
    a11y: {},
    legacyType: "compound",
    tags: ["payment", "iban", "bank"],
  },
  {
    id: "tax-id-uk",
    label: "UK tax / VAT number",
    category: "payment",
    summary: "VAT or UTR with format validation.",
    runner: "compound.tax-id",
    csv: { columns: 1 },
    defaultValidation: { named: ["vat-uk"] },
    a11y: {},
    legacyType: "text",
    tags: ["tax", "vat", "uk"],
  },
  {
    id: "tax-id-intl",
    label: "International tax ID",
    category: "payment",
    summary: "Country-aware tax ID — EIN, SSN, VAT, etc.",
    runner: "compound.tax-id",
    csv: { columns: 2, columnSuffixes: ["country", "id"] },
    defaultValidation: {},
    a11y: {},
    legacyType: "compound",
    tags: ["tax", "id", "international"],
  },

  // ───────── legal ─────────
  {
    id: "nda-accept",
    label: "NDA acceptance",
    category: "legal",
    summary: "Tick to accept the NDA — audit-logged.",
    runner: "compound.consent",
    csv: { columns: 1, transform: "boolean-yn" },
    defaultValidation: { required: true },
    a11y: {},
    legacyType: "checkbox",
    tags: ["nda", "legal", "consent"],
  },
  {
    id: "consent-gdpr",
    label: "GDPR consent",
    category: "legal",
    summary: "Tick to consent to data processing.",
    runner: "compound.consent",
    csv: { columns: 1, transform: "boolean-yn" },
    defaultValidation: { required: true },
    a11y: {},
    legacyType: "checkbox",
    tags: ["gdpr", "legal", "consent"],
  },
  {
    id: "consent-marketing",
    label: "Marketing consent",
    category: "legal",
    summary: "Optional tick to receive marketing.",
    runner: "compound.consent",
    csv: { columns: 1, transform: "boolean-yn" },
    defaultValidation: {},
    a11y: {},
    legacyType: "checkbox",
    tags: ["marketing", "consent", "optional"],
  },

  // ───────── layout ─────────
  {
    id: "heading",
    label: "Section heading",
    category: "layout",
    summary: "Visual heading. Not a data field.",
    runner: "layout.heading",
    csv: { columns: 0 },
    defaultValidation: {},
    a11y: {},
    legacyType: "compound",
    tags: ["layout", "heading"],
  },
  {
    id: "helper-text",
    label: "Helper text",
    category: "layout",
    summary: "Inline guidance paragraph. Not a data field.",
    runner: "layout.helper",
    csv: { columns: 0 },
    defaultValidation: {},
    a11y: {},
    legacyType: "compound",
    tags: ["layout", "helper"],
  },
  {
    id: "divider",
    label: "Divider",
    category: "layout",
    summary: "Horizontal rule between groups of fields.",
    runner: "layout.divider",
    csv: { columns: 0 },
    defaultValidation: {},
    a11y: {},
    legacyType: "compound",
    tags: ["layout", "divider"],
  },
  {
    id: "repeater",
    label: "Repeating group",
    category: "layout",
    summary: "Author groups inner fields; user adds N copies.",
    runner: "compound.repeater",
    csv: { columns: 1 }, // serialised as JSON array
    defaultValidation: {},
    a11y: {},
    legacyType: "compound",
    tags: ["repeater", "group", "array"],
  },

  // ───────── advanced ─────────
  {
    id: "conditional-reveal",
    label: "Conditional reveal",
    category: "advanced",
    summary: "Wrap a field; show only when condition matches.",
    runner: "logic.conditional-reveal",
    csv: { columns: 0 },
    defaultValidation: {},
    a11y: {},
    legacyType: "compound",
    tags: ["logic", "conditional", "advanced"],
  },
];
