import { Field, PackSchema } from "../schemas/types";

/**
 * Google Forms / Apps Script JSON spec.
 *
 * The buyer pastes this into Apps Script (Tools → Script Editor) and runs
 * `createForm(spec)` to recreate the pack as a Google Form. The function is
 * generated alongside the spec and shipped as a .gs file in the README.
 *
 * Output is a single .json file. We expose two named exports — the spec
 * builder, and the snippet of Apps Script that consumes it.
 */

export interface GFormsSpec {
  meta: {
    pack_id: string;
    title: string;
    generated_at: string;
    pathways: { id: string; name: string }[];
  };
  sections: Array<{
    id: string;
    name: string;
    intro?: string;
    fields: GFormsField[];
  }>;
}

interface GFormsField {
  id: string;
  label: string;
  type: "text" | "paragraph" | "date" | "multipleChoice" | "checkbox" | "number" | "email";
  required: boolean;
  options?: string[];
  pathways?: string[];
  regulator?: string;
}

export function buildGFormsSpec(schema: PackSchema): GFormsSpec {
  return {
    meta: {
      pack_id: schema.productId,
      title: schema.title,
      generated_at: new Date().toISOString(),
      pathways: schema.pathways,
    },
    sections: schema.sections.map((s) => ({
      id: s.id,
      name: s.name,
      intro: s.intro,
      fields: s.fields.map(toGFormsField),
    })),
  };
}

function toGFormsField(f: Field): GFormsField {
  return {
    id: f.id,
    label: f.label,
    type: typeMap(f),
    required: !!f.required,
    options: f.options,
    pathways: f.pathways,
    regulator: f.regulator,
  };
}

function typeMap(f: Field): GFormsField["type"] {
  switch (f.type) {
    case "textarea":
      return "paragraph";
    case "select":
    case "multi-select":
      return "multipleChoice";
    case "checkbox":
      return "checkbox";
    case "date":
      return "date";
    case "number":
      return "number";
    case "email":
      return "email";
    default:
      return "text";
  }
}

/**
 * Apps Script snippet shipped alongside the spec. Buyer pastes into
 * Tools → Script Editor on a fresh Google Form, replaces SPEC with the
 * downloaded JSON, and runs `createForm()` once.
 */
export const APPS_SCRIPT_TEMPLATE = `/**
 * Kapture Forms · Google Forms importer
 * Paste into Tools → Script Editor on a fresh Google Form,
 * replace SPEC below with the downloaded JSON, then run createForm().
 */
const SPEC = {/* paste-here */};

function createForm() {
  const form = FormApp.create(SPEC.meta.title);
  form.setDescription(
    'Pathways: ' + SPEC.meta.pathways.map(p => p.name).join(' · ') +
    '\\nGenerated by Kapture Forms · forms.thekapture.com'
  );
  form.addMultipleChoiceItem()
    .setTitle('Pathway')
    .setRequired(true)
    .setChoiceValues(SPEC.meta.pathways.map(p => p.name));

  SPEC.sections.forEach(section => {
    form.addPageBreakItem().setTitle(section.name).setHelpText(section.intro || '');
    section.fields.forEach(field => {
      let item;
      switch (field.type) {
        case 'paragraph':  item = form.addParagraphTextItem(); break;
        case 'multipleChoice':
          item = form.addMultipleChoiceItem();
          if (field.options) item.setChoiceValues(field.options);
          break;
        case 'checkbox':   item = form.addCheckboxItem(); break;
        case 'date':       item = form.addDateItem(); break;
        case 'number':     item = form.addTextItem().setValidation(
          FormApp.createTextValidation().requireNumber().build()
        ); break;
        case 'email':      item = form.addTextItem().setValidation(
          FormApp.createTextValidation().requireTextIsEmail().build()
        ); break;
        default:           item = form.addTextItem();
      }
      const label = field.label + (field.regulator ? '  [' + field.regulator + ']' : '');
      item.setTitle(label).setRequired(!!field.required);
    });
  });

  Logger.log('Form URL: ' + form.getEditUrl());
  Logger.log('Public URL: ' + form.getPublishedUrl());
}
`;
